baseURL = "https://www.codesirpi.com/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "CodeSirpi"
favicon = "images/favicon.ico"
[markup.goldmark.renderer]
unsafe = true
