baseURL = "https://www.codesirpi.com/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "CodeSirpi"
favicon = "images/favicon.ico"
[markup.goldmark.renderer]
unsafe = true
[params]
typeformid = "EMf8yma2"
typeformuser = "sundar82" # Optional
typeformwidth = "100%" # Optional
[params.variables]
primary_color = "#6C63FF"